name: Greetings

on:
  push:
    branches:
      - '*'
      - '!master'
jobs:
  job1:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: Group of log lines
      run: |
          echo "::group::My title"
          echo "Inside group"
          echo "::endgroup::"
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Message that will be displayed on users' first issue"
        pr-message: "Message that will be displayed on users' first pull request"
